### ISSUE TITLE
call_user_func() expects parameter 1 to be a valid callback, no array

### ISSUE THREAD

**Issue by adjoines** [gabizz/Twig-Helper-for-simple-mvc-framework#1]
I installed SMVCf and twig using composer.
When I try to use  the twig helper, I am getting this error.
Error on Dec 21, 2015 12:04PM - call_user_func() expects parameter 1 to be a valid callback, no array or string given in E:\xampp\htdocs\sitename\vendor\twig\twig\lib\Twig\Extension\Escaper.php on line 73

**Comment by gabizz** [comment]
could you please provide more details. typically, you should "send" data from the controller to the view (twig template file), by using Twig::render('file.tpl', $data).... The variable $data may contain. for example, $data['queryresult'] as an associative array [0]=>id,,,,,, [1]=>id....  In this case, you output in twig: {{queryresult.0.id}} . keep me updated with your progress.

**Comment by adjoines** [comment]
That's just the error I get. nothing else
Error on Dec 21, 2015 12:04PM - call_user_func() expects parameter 1 to be a valid callback, no array or string given in E:\xampp\htdocs\sitename\vendor\twig\twig\lib\Twig\Extension\Escaper.php on line 73

<?php
/**
- Welcome controller
  *
- @author David Carr - dave@daveismyname.com
- @version 2.2
- @date June 27, 2014
- @date updated Sept 19, 2015
  */

namespace Controllers;

use Core\View;
use Core\Controller;
use helpers\Twig;
/**
- Sample controller showing a construct and 2 methods and their typical usage.
  */
  class Welcome extends Controller
  {
  
  /**
  - Call the parent construct
    */
    public function __construct()
    {
    parent::__construct();
    $this->language->load('Welcome');
    }
  
  /**
  - Define Index page title and load template files
    */
    public function index()
    {
    $data['title'] = $this->language->get('welcome_text');
    $data['welcome_message'] = $this->language->get('welcome_message');
    
    //View::renderTemplate('header', $data);
    Twig::render('welcome/welcome', $data);
    // View::renderTemplate('footer', $data);
    }
    }

**Comment by gabizz** [comment]
ok. this is the controller. I assume you have created besides this a view file in app/views/welcome/welcome.tpl and inside it you are trying to output {{ welcome_message }}. is that right?

one more idea: you could set 'strict_variables' =>  false in line 56

for debuging purposes, you should also try to set 'autoescape' => false ...(your error tells actualy that the autoescaping strategy is wrong or that there is nothing to escape)

i am using it extensively in the app I'm working on right now and haven't encounter any issues so far..

**Comment by adjoines** [comment]
It work's well if  'autoescape' => false .  I don't know what is it .....I am missing.

**Comment by gabizz** [comment]
Do a simple test for debugging. Re-enable autoescape, and in your controller type somewhere $data['name'] = "Ericel"; 
Then, in your welcome.tpl file, make sure that are no other twig expressions than {{name}}
If it works, in the controller add an echo before $data['welcome_message'] = $this->language->get('welcome_message'); Refresh the page and if it doesn't output the welcome message, there you go, the problem is that the welcome_message has not been defined. 
Please keep me update, I am curious.

**Comment by adjoines** [comment]
I still get the weird error when I re-enable 'autoescape'.
Error on Dec 22, 2015 7:48AM - call_user_func() expects parameter 1 to be a valid callback, no array or string given in E:\xampp\htdocs\sitename\vendor\twig\twig\lib\Twig\Extension\Escaper.php on line 73

**Comment by adjoines** [comment]
I think I figured it out. The continuous error has something to do with the caching.  ('cache' =>  'cache')...Once an error is caught , It will keep showing error even after the app seems to be working fine.

**Comment by adjoines** [comment]
How do you go about using Simple MVC helpers in the twig template? example -> use Helpers\Url;....How to I add this to my twig template?

**Comment by gabizz** [comment]
Wipe the directory cache and try again :)

--- How do you go about using Simple MVC helpers in the twig template? example -> use Helpers\Url;....How to I add this to my twig template? ---

You don't :) That's the beauty. You are force to work "the proper way". That statement should stay within the controller. By using twig you are bound to do things rightly and securely and in accordance with the MVC good practices. (I admit, before using twig, I've often fallen under the temptation of writing queries within the view or using helpers in the view). My first apps were like this. (and now I find it hell difficult to maintain them).

Basically, you may send all kind of data to twig template (arrays, valuest etc.) and then use the twig logic to loop them. Twig is a genial thing that takes care of the rest (executing nice php code in cache for what you do).

Anything you need, send it to the template from the controller through $data variable. I, sometimes find it useful to write $data['path'] = DIR; and that inside the template, whenever I need the absolute path I use {{path}} expression. Of course, in the same function I also send the query result to the same template using eg: $data['queryresult']... and any other stuff I need.

Sometimes, when delegating jQuery events to make them work in JQueryUI modal (for example), getting the ajax path gets complicated. So, I just use for the selected element, a 'data' atribute... eg: <div class = "some-element" data-path = "{{path}}"></div> and then I use it in js as a part of ajax url. This way you cannot get wrong. 

Hope I wasn't too long.

Gabriel

**Comment by adjoines** [comment]
Thanks so much. It works just perfect. Are you using a helper to declare variables that are used on every view, or u just go ahead and repeat them on each controller method.

Example the $data[temp_path] = Url::templatePath();.
Am tempted to hard coding it in my config file rather than repeating it on each controller method. 

Any suggestions...

**Comment by gabizz** [comment]
I'm glad you made it work.  
a
As concernes the other question...  I guess it's up to you.  In the end it's a matter of ergonomics.  I personally,  prefer to see al the stuff I'm sending to the view in the beginning of each controller's method,  so I may debug anything easier later if I need to. I create helpers to do things that tend to repeat.  Eg. getStuff(id,  property),  but again, I don't thing that there is an universal rule.  
I learn everyday,  just like you do and very often I say to my self when reviewing some piece of code I wrote 6 months ago: "with the 'brains' I have today I  would have done that so much simpler :) " and I'm sure that will happen to me all the time as I learn more stuff :)

**Comment by cinder92** [comment]
im having same issue with codeigniter
